version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - setup_remote_docker
      - run: docker build -t negan-server .
      - run: docker image ls  # Kiểm tra image đã build xong chưa

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
