version: 2.1

jobs:
  build-and-push:
    docker:
      - image: circleci/docker:latest
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Build Docker Image
          command: docker build -t my-image:latest .
      - run:
          name: Login to Docker Hub
          command: echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
      - run:
          name: Push Docker Image
          command: docker tag my-image:latest $DOCKER_USER/my-image:latest && docker push $DOCKER_USER/my-image:latest

workflows:
  version: 2
  deploy:
    jobs:
      - build-and-push
